"""Converts images to TFRecords file format.

This skript converts the images generated by generateSimpleDataset.py into the
TFRecords file format.

Adapted from https://github.com/tensorflow/tensorflow/blob/r1.3/tensorflow/
             examples/how_tos/reading_data/convert_to_records.py
"""
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import argparse
import os
import sys
import csv
import imageio
from PIL import Image

from pdb import set_trace as bp

import tensorflow as tf

FLAGS = None


def _int64_feature(value):
    return tf.train.Feature(int64_list=tf.train.Int64List(value=[value]))


def _bytes_feature(value):
    return tf.train.Feature(bytes_list=tf.train.BytesList(value=[value]))


def convert_to(inputDir, name):
    """Converts images dataset to tfrecords."""
    imagePaths = []
    labelPath = None
    print('Looking for images...')
    for (dirPath, dirNames, fileNames) in os.walk(inputDir):
        for fileName in fileNames:
            if fileName[-4:] == '.png':
                imagePaths.append(os.path.join(dirPath, fileName))
            elif fileName == 'labels.csv':
                labelPath = os.path.join(dirPath, fileName)

    if labelPath is None:
        raise ValueError('No label file found. Must be named labels.csv')

    labels = []
    with open(labelPath, newline='') as csvfile:
        csvreader = csv.reader(csvfile, delimiter=';', quotechar='|')
        for row in csvreader:
            labels.append(row[0])

    num_examples = len(labels)
    if len(imagePaths) != num_examples:
        raise ValueError('Number of images %d does not match label size %d.' %
                         (len(imagePaths), num_examples))

    rows = 64
    cols = 64
    depth = 3
    imagePaths = sorted(imagePaths)
    bp()

    filename = os.path.join(FLAGS.output, name + '.tfrecords')
    writer = tf.python_io.TFRecordWriter(filename)

    print('Writing records to ' + filename + ' ...')
    for index in range(num_examples):
        if index % 1000 == 0:
            print('\t' + 'Write image ' + repr(index))
        imageRaw = imageio.imread(imagePaths[index])
        example = tf.train.Example(features=tf.train.Features(feature={
            'height': _int64_feature(rows),
            'width': _int64_feature(cols),
            'depth': _int64_feature(depth),
            'label': _int64_feature(int(labels[index])),
            'name': _bytes_feature(imagePaths[index]),
            'image_raw': _bytes_feature(imageRaw.tostring())}))
        writer.write(example.SerializeToString())
    writer.close()


def main(unused_argv):

    convert_to(FLAGS.input, 'train')


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument(
        '--output',
        type=str,
        default='./',
        help='Directory to write the converted result'
    )
    parser.add_argument(
        '--input',
        type=str,
        default='./images',
        help='Directory of the images and labels'
    )
    FLAGS, unparsed = parser.parse_known_args()
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
